---
# ./roles/influxdb/tasks/service.yml

- name: Start influxdb service
  become: yes
  become_user: root
  become_method: su
  service: name=influxdb state=started
  tags:
    - influxdb
    - start_influxdb

- name: Stop influxdb service
  become: yes
  become_user: root
  become_method: su
  service: name=influxdb state=stopped
  tags:
    - influxdb
    - stop_influxdb

- name: Restart influxdb service
  become: yes
  become_user: root
  become_method: su
  service: name=influxdb state=restarted
  tags:
    - influxdb
    - restart_influxdb
